name: "Build"
on:
  pull_request:
  push:
jobs:
  tests:
    timeout-minutes: 420
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - run: sudo rm -rf /opt || true
    - uses: actions/checkout@v2.3.2
    - uses: cachix/install-nix-action@v11
    - uses: cachix/cachix-action@v6
      with:
        name: ghcide-nix
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: |
        nix-build \
          --substituters https://hydra.iohk.io \
          --trusted-public-keys hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
